name: pwa_to_flutter_app
description: Tirhal Driver App - PWA to Flutter with OneSignal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # المكتبات الأساسية
  flutter_inappwebview: ^6.0.0
  onesignal_flutter: ^3.2.7   # النسخة القديمة المستقرة
  vibration: ^1.8.4
  audioplayers: ^5.2.1
  connectivity_plus: ^5.0.0
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # ملف الصوت المحلي
  assets:
    - assets/ride_request_sound.wav